---
- name: Check node_exporter exist.
  stat:
    path: "{{ node_exporter_bin_path }}"
  register: node_exporter_check

- name: Download and unarchive node_exporter into temporary location.
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: not node_exporter_check.stat.exists

- name: Move node_exporter binary into place.
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart node_exporter
  when: not node_exporter_check.stat.exists

- name: Create node_exporter user.
  user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the node_exporter environment file.
  template:
    src: node_exporter.j2
    dest: /etc/default/node_exporter
    mode: 0644
  notify: restart node_exporter

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  register: node_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: Ensure node_exporter is running and enabled at boot.
  service:
    name: node_exporter
    state: started
    enabled: true

- name: Verify node_exporter is responding to requests.
  uri:
    url: "http://localhost:9100/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"

