---
# Use prometheus release
prometheus_version: '2.40.6'

prometheus_download_url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz

prometheus_bin_path: /usr/local/bin/prometheus

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_options: 'OPTIONS="--config.file={{ prometheus_config_dir }}/prometheus.yml --storage.tsdb.path={{ prometheus_db_dir }}/"'

# A scrape configuration containing exactly one endpoint to scrape
prometheus_static_config:
   - job_name: 'static_config'
     static_configs:
     - targets:
         - localhost:9100

prometheus_file_sd_config: []
#   - job_name: 'file_sd'
#     file_sd_configs:
#       - files:
#         - "{{ prometheus_config_dir }}/sd/*.yml"
#         refresh_interval: 1m