---
- name: Add required dependencies.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Fluent Bit apt key.
  apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Add Fluent Bit repository.
  apt_repository:
    repo: 'deb https://packages.fluentbit.io/ubuntu/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main'
    state: present
    update_cache: true