version: "2.1"
services:
  app:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
