---
- name: "{{ app_name }} install and configure" 
  hosts: app
  vars:
    app_name: xpaste
    app_path: /app/
    app_socket: /tmp/puma.sock
    app_user: s045724
    db_host: 127.0.0.1
    db_port: 5432
    db_name: xpaste
    db_user: xpaste
    db_password: password
    secret_key: secret
  
  pre_tasks:
  - name: "Put SELinux in permissive mode"
    ansible.posix.selinux:
      policy: targeted
      state: permissive
    become: true

  roles:
     - { name: postgres, become: true }
     - { name: geerlingguy.nginx , become: true }   
     - webapp  
  
  post_tasks:
  - name: "Ensure {{ app_name }} service is running"
    ansible.builtin.service:
      name: '{{ app_name }}.service'
      state: started
    become: true 
